#!/usr/bin/env node
require('dotenv').config();
const { neon } = require('@neondatabase/serverless');

const DATABASE_URL = process.env.EXPO_PUBLIC_DATABASE_URL;
if (!DATABASE_URL) { console.error('Error: DATABASE_URL not found'); process.exit(1); }
const sql = neon(DATABASE_URL);

const allQuestions = [
  // TECHNICIAN STEP 1 (15)
  { role: "technician", step: 1, question_text_en: "Which cell technology is most commonly used in EV batteries?", question_text_hi: "EV बैटरी में सबसे सामान्य रूप से कौन सी सेल तकनीक उपयोग की जाती है?", question_text_mr: "EV बॅटरीमध्ये सामान्यतः कोणती सेल तंत्रज्ञान वापरले जाते?", question_text_kn: "EV ಬ್ಯಾಟರಿಗಳಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಯಾವ ಸೆಲ್ ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ?", question_text_te: "EV బ్యాటరీలలో సాధారణంగా ఏ సెల్ టెక్నాలజీని ఉపయోగిస్తారు?", question_text_or: "EV ବ୍ୟାଟେରୀରେ ସାଧାରଣତଃ କେଉଁ ସେଲ୍ ଟେକ୍ନୋଲୋଜି ବ୍ୟବହୃତ ହୁଏ?", options: [{ en: "Lead-Acid", hi: "लीड-एसिड", mr: "लेड-ॲसिड", kn: "ಲೆಡ್-ಆಸಿಡ್", te: "లెడ్-యాసిడ్", or: "ଲେଡ୍-ଏସିଡ୍", isCorrect: false }, { en: "Lithium-Ion", hi: "लिथियम-आयन", mr: "लिथियम-आयन", kn: "ಲಿಥಿಯಂ-ಐಯಾನ್", te: "లిథియం-అయాన్", or: "ଲିଥିୟମ୍-ଆୟନ", isCorrect: true }, { en: "Nickel-Cadmium", hi: "निकल-कैडमियम", mr: "निकेल-कॅडमियम", kn: "ನಿಕಲ್-ಕ್ಯಾಡ್ಮಿಯಮ್", te: "నికెల్-కాడ్మియం", or: "ନିକେଲ୍-କ୍ୟାଡମିୟମ୍", isCorrect: false }, { en: "Zinc-Carbon", hi: "जिंक-कार्बन", mr: "झिंक-कार्बन", kn: "ಜಿಂಕ್-ಕಾರ್ಬನ್", te: "జింక్-కార్బన్", or: "ଜିଙ୍କ-କାର୍ବନ", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "What is the full form of BMS?", question_text_hi: "BMS का पूरा नाम क्या है?", question_text_mr: "BMS चे पूर्ण रूप काय आहे?", question_text_kn: "BMS ನ ಪೂರ್ಣ ರೂಪವೇನು?", question_text_te: "BMS అంటే పూర్తి రూపం ఏమిటి?", question_text_or: "BMS ର ପୂର୍ଣ୍ଣ ରୂପ କଣ?", options: [{ en: "Battery Monitoring System", hi: "बैटरी मॉनिटरिंग सिस्टम", mr: "बॅटरी मॉनिटरिंग सिस्टम", kn: "ಬ್ಯಾಟರಿ ಮಾನಿಟರಿಂಗ್ ಸಿಸ್ಟಮ್", te: "బ్యాటరీ మానిటరింగ్ సిస్టమ్", or: "ବ୍ୟାଟେରୀ ମନିଟରିଂ ସିଷ୍ଟମ", isCorrect: false }, { en: "Battery Management System", hi: "बैटरी मैनेजमेंट सिस्टम", mr: "बॅटरी मॅनेजमेंट सिस्टम", kn: "ಬ್ಯಾಟರಿ ಮ್ಯಾನೇಜ್ಮೆಂಟ್ ಸಿಸ್ಟಮ್", te: "బ్యాటరీ మేనేజ్మెంట్ సిస్టమ్", or: "ବ୍ୟାଟେରୀ ମ୍ୟାନେଜମେଣ୍ଟ ସିଷ୍ଟମ", isCorrect: true }, { en: "Basic Motor System", hi: "बेसिक मोटर सिस्टम", mr: "बेसिक मोटर सिस्टम", kn: "ಬೇಸಿಕ್ ಮೋಟಾರ್ ಸಿಸ್ಟಮ್", te: "బేసిక్ మోటార్ సిస్టమ్", or: "ବେସିକ ମୋଟର ସିଷ୍ଟମ", isCorrect: false }, { en: "Balanced Mode System", hi: "बैलेंस्ड मोड सिस्टम", mr: "बॅलन्स्ड मोड सिस्टम", kn: "ಬ್ಯಾಲೆನ್ಸ್ಡ್ ಮೋಡ್ ಸಿಸ್ಟಮ್", te: "బ్యాలెన్స్డ్ మోడ్ సిస్టమ్", or: "ବ୍ୟାଲେନ୍ସଡ ମୋଡ ସିଷ୍ଟମ", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "What does BLDC motor mean in EV?", question_text_hi: "EV में BLDC मोटर का क्या अर्थ है?", question_text_mr: "EV मध्ये BLDC मोटरचा अर्थ काय?", question_te  { role: "technician", step: 1, question_text_en: "What does BLDC motor mean in EV?", question_text_hi: "EV में BLDC मोटर का क्या अर्थ है?", questiରେ BLDC ମୋଟରର ଅର୍ଥ କଣ?", options: [{ en: "Brushed Direct Current", hi: "ब्रश्ड डायरेक्ट करंट", mr: "ब्रश्ड डायरेक्ट करंट", kn: "ಬ್ರಷ್ಡ್ ಡೈರೆಕ್ಟ್ ಕರೆಂಟ್", te: "బ్రష్డ్ డైరెక్ట్ కరెంట్", or: "ବ୍ରଶଡ୍ ଡାଇରେକ୍ଟ କରେଣ୍ଟ", isCorrect: false }, { en: "Brushless Direct Current", hi: "ब्रशलेस डायरेक्ट करंट", mr: "ब्रशलेस डायरेक्ट करंट", kn: "ಬ್ರಷ್ಲೆಸ್ ಡೈರೆಕ್ಟ್ ಕರೆಂಟ್", te: "బ్రష్లెస్ డైరెక్ట్ కరెంట్", or: "ବ୍ରଶଲେସ୍ ଡାଇରେକ୍ଟ କରେଣ୍ଟ", isCorrect: true }, { en: "Basic Low Drive Current", hi: "बेसिक लो ड्राइव करंट", mr: "बेसिक लो ड्राइव करंट", kn: "ಬೇಸಿಕ್ ಲೋ ಡ್ರೈವ್ ಕರೆಂಟ್", te: "బేసిక్ లో డ్రైవ్ కరెంట్", or: "ବେସିକ ଲୋ ଡ୍ରାଇଭ କରେଣ୍ଟ", isCorrect: false }, { en: "Balanced Load Distribution Current", hi: "बैलेंस्ड लोड डिस्ट्रीब्यूशन करंट", mr: "बॅलन्स्ड लोड डिस्ट्रिब्युशन करंट", kn: "ಬ್ಯಾಲೆನ್ಸ್ಡ್ ಲೋಡ್ ಡಿಸ್ಟ್ರಿಬ್ಯೂಷನ್ ಕರೆಂಟ್", te: "బ్యాలెన్స్డ్ లోడ్ డిస్ట్రిబ్యూషన్ కరెంట్", or: "ବ୍ୟାଲେନ୍ସଡ ଲୋଡ ଡିଷ୍ଟ୍ରିବ୍ୟୁସନ କରେଣ୍ଟ", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "What is the function of regenerative braking?", question_text_hi: "रीजनरेटिव ब्रेकिंग का क्या काम है?", question_text_mr: "रिजनरेटिव्ह ब्रेकिंगचे कार्य काय आहे?", question_text_kn: "ರಿಜನರೇಟಿವ್ ಬ್ರೇಕಿಂಗ್ನ ಕೆಲಸವೇನು?", question_text_te: "రీజెనరేటివ్ బ్రేకింగ్ పని ఏమిటి?", question_text_or: "ରିଜେନେରେଟିଭ୍ ବ୍ରେକିଂର କାମ କଣ?", options: [{ en: "Increase speed", hi: "गति बढ़ाना", mr: "वेग वाढवणे", kn: "ವೇಗ ಹೆಚ್ಚಿಸುವುದು", te: "వేగం పెంచడం", or: "ଗତି ବଢାଇବା", isCorrect: false }, { en: "Send energy back to battery during braking", hi: "ब्रेकिंग के दौरान ऊर्जा वापस बैटरी में भेजना", mr: "ब्रेकिंग दरम्यान ऊर्जा बॅटरीमध्ये परत पाठवणे", kn: "ಬ್ರೇಕಿಂಗ್ ಸಮಯದಲ್ಲಿ ಶಕ್ತಿಯನ್ನು ಮತ್ತೆ ಬ್ಯಾಟರಿಗೆ ಕಳುಹಿಸುವುದು", te: "బ్రేకింగ్ సమయంలో శక్తిని తిరిగి బ్యాటరీకి పంపడం", or: "ବ୍ରେକିଂ ସମୟରେ ଶକ୍ତିକୁ ପୁନର୍ବାର ବ୍ୟାଟେରୀକୁ ପଠାଇବା", isCorrect: true }, { en: "Increase tire grip", hi: "टायर की पकड़ बढ़ाना", mr: "टायरची पकड वाढवणे", kn: "ಟೈರ್ ಗ್ರಿಪ್ ಹೆಚ್ಚಿಸುವುದು", te: "టైర్ గ్రిప్ పెంచడం", or: "ଟାୟାର୍ ଗ୍ରିପ୍ ବଢାଇବା", isCorrect: false }, { en: "Cool down the motor", hi: "मोटर को ठंडा करना", mr: "मोटार थंड करणे", kn: "ಮೋಟಾರ್ ತಂಪಾಗಿಸುವುದು", te: "మోటారును చల్లబరచడం", or: "ମୋଟରକୁ ଥଣ୍ଡା କରିବା", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "In what unit is EV battery capacity measured?", question_text_hi: "EV बैटरी की क्षमता किसमें मापी जाती है?", question_text_mr: "EV बॅटरीची क्षमता कशात मोजली जाते?", question_text_kn: "EV ಬ್ಯಾಟರಿ ಸಾಮರ್ಥ್ಯವನ್ನು ಯಾವ ಘಟಕದಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ?", question_text_te: "EV బ్యాటరీ సామర్థ్యాన్ని ఏ యూనిట్లో కొలుస్తారు?", question_text_or: "EV ବ୍ୟାଟେରୀ କ୍ଷମତା କେଉଁ ୟୁନିଟରେ ମାପ ହୁଏ?", options: [{ en: "Watt (W)", hi: "वाट (W)", mr: "वॅट (W)", kn: "ವ್ಯಾಟ್ (W)", te: "వాట్ (W)", or: "ୱାଟ୍ (W)", isCorrect: false }, { en: "Kilowatt-hour (kWh)", hi: "किलोवाट-ऑवर (kWh)", mr: "किलोवॅट-अवर (kWh)", kn: "ಕಿಲೋವ್ಯಾಟ್-ಅವರ್ (kWh)", te: "కిలోవాట్-అవర్ (kWh)", or: "କିଲୋୱାଟ-ଆୱାର (kWh)", isCorrect: true }, { en: "Ampere (A)", hi: "एम्पियर (A)", mr: "अँपिअर (A)", kn: "ಆಂಪಿಯರ್ (A)", te: "ఆంపియర్ (A)", or: "ଏମ୍ପିୟର (A)", isCorrect: false }, { en: "Volt (V)", hi: "वोल्ट (V)", mr: "व्होल्ट (V)", kn: "ವೋಲ್ಟ್ (V)", te: "వోల్ట్ (V)", or: "ଭୋଲ୍ଟ (V)", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "What is thermal runaway?", question_text_hi: "थर्मल रनवे क्या है?", question_text_mr: "थर्मल रनवे म्हणजे काय?", question_text_kn: "ಥರ್ಮಲ್ ರನ್ಅವೇ ಎಂದರೇನು?", question_text_te: "థర్మల్ రన్అవే అంటే ఏమిటి?", question_text_or: "ଥର୍ମାଲ୍ ରନୱେ କଣ?", options: [{ en: "Normal battery temp", hi: "बैटरी का सामान्य तापमान", mr: "बॅटरीचे सामान्य तापमान", kn: "ಬ್ಯಾಟರಿಯ ಸಾಮಾನ್ಯ ತಾಪಮಾನ", te: "సాధారణ బ్యాటరీ ఉష్ణోగ్రత", or: "ବ୍ୟାଟେରୀର ସାଧାରଣ ତାପମାତ୍ରା", isCorrect: false }, { en: "Uncontrolled rise in heat", hi: "बैटरी में अनियंत्रित गर्मी का बढ़ना", mr: "बॅटरीमध्ये उष्णतेची अनियंत्रित वाढ", kn: "ಬ್ಯಾಟರಿಯಲ್ಲಿ ಶಾಖದ ಅನಿಯಂತ್ರಿತ ಏರಿಕೆ", te: "బ్యాటరీలో అదుపులేని వేడి పెరుగుదల", or: "ବ୍ୟାଟେରୀରେ ଅନିୟନ୍ତ୍ରିତ ଉତ୍ତାପ ବୃଦ୍ଧି", isCorrect: true }, { en: "Motor cooling", hi: "मोटर का ठंडा होना", mr: "मोटार थंड करणे", kn: "ಮೋಟಾರ್ ಕೂಲಿಂಗ್", te: "మోటారు శీతలీకరణ", or: "ମୋଟର କୁଲିଂ", isCorrect: false }, { en: "Normal charging", hi: "चार्जिंग की सामान्य प्रक्रिया", mr: "सामान्य चार्जिंग प्रक्रिया", kn: "ಸಾಮಾನ್ಯ ಚಾರ್ಜಿಂಗ್", te: "సాధారణ ఛార్జింగ్", or: "ସାଧାରଣ ଚାର୍ଜିଂ", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What is the function of controller in EV?", question_text_hi: "EV में कंट्रोलर का क्या काम है?", question_text_mr: "EV मध्ये कंट्रोलरचे कार्य काय आहे?", question_text_kn: "EV ನಲ್ಲಿ ಕಂಟ್ರೋಲರ್ನ ಕೆಲಸವೇನು?", question_text_te: "EVలో కంట్రోలర్ పని ఏమిటి?", question_text_or: "EV ରେ କଣ୍ଟ୍ରୋଲରର କାମ କଣ?", options: [{ en: "Charge battery", hi: "बैटरी चार्ज करना", mr: "बॅटरी चार्ज करणे", kn: "ಬ್ಯಾಟರಿ ಚಾರ್ಜ್", te: "బ్యాటరీ ఛార్జింగ్", or: "ବ୍ୟାଟେରୀ ଚାର୍ଜିଂ", isCorrect: false }, { en: "Control speed and torque", hi: "मोटर की गति और टॉर्क नियंत्रित करना", mr: "मोटार वेग आणि टॉर्क नियंत्रित करणे", kn: "ವೇಗ ಮತ್ತು ಟಾರ್ಕ್ ನಿಯಂತ್ರಣ", te: "వేగం మరియు టార్క్ నియంత్రణ", or: "ଗତି ଏବଂ ଟର୍କ ନିୟନ୍ତ୍ରଣ", isCorrect: true }, { en: "Change tires", hi: "टायर बदलना", mr: "टायर बदलणे", kn: "ಟೈರ್ ಬದಲಾವಣೆ", te: "టైర్లు మార్చడం", or: "ଟାୟାର ବଦଳାଇବା", isCorrect: false }, { en: "Fill fuel", hi: "ईंधन भरना", mr: "इंधन भरणे", kn: "ಇಂಧನ ತುಂಬಿಸುವುದು", te: "ఇంధనం నింపడం", or: "ଇନ୍ଧନ ଭରିବା", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What is the use of DC-DC converter?", question_text_hi: "DC-DC कनवर्टर का क्या उपयोग है?", question_text_mr: "DC-DC कन्व्हर्टरचा उपयोग काय आहे?", question_text_kn: "DC-DC ಪರಿವರ್ತಕದ ಉಪಯೋಗವೇನು?", question_text_te: "DC-DC కన్వర్టర్ ఉపయోగం ఏమిటి?", question_text_or: "DC-DC କନଭର୍ଟରର ବ୍ୟବହାର କଣ?", options: [{ en: "High to low voltage", hi: "उच्च वोल्टेज को निम्न वोल्टेज में बदलना", mr: "उच्च ते कमी व्होल्टेज", kn: "ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ ವೋಲ್ಟೇಜ್", te: "హై టు లో వోల్టేజ్", or: "ଉଚ୍ଚରୁ ନିମ୍ନ ଭୋଲ୍ଟେଜ୍", isCorrect: true }, { en: "AC to DC", hi: "AC को DC में बदलना", mr: "AC ते DC", kn: "AC ಇಂದ DC", te: "AC నుండి DC", or: "AC ରୁ DC", isCorrect: false }, { en: "Increase speed", hi: "मोटर की गति बढ़ाना", mr: "वेग वाढवणे", kn: "ವೇಗ ಹೆಚ್ಚಳ", te: "వేగం పెంచడం", or: "ଗତି ବଢାଇବା", isCorrect: false }, { en: "Cool battery", hi: "बैटरी को ठंडा करना", mr: "बॅटरी थंड करणे", kn: "ಬ್ಯಾಟರಿ ತಂಪಾಗಿಸುವುದು", te: "బ్యాటరీ కూలింగ్", or: "ବ୍ୟାଟେରୀ କୁଲିଂ", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What does SOC mean in EV?", question_text_hi: "EV में सोक (SOC) का क्या अर्थ है?", question_text_mr: "EV मध्ये SOC चा अर्थ काय आहे?", qu  { role: "technician", step: 1, question_text_en: "What does SOC mean in EV?", question_text_hi: "EV में सोक (SOC) का क्या अर्थ है?", question_text_mr: "EV मध्ये SOC चा अर्थ काय आहे?", qu  { role: "technician", step: 1, question_text_en: "What does SOC mean in EV?", question_text_hi: "EV में सोक (SOC) का क्या अर्थ है?", question_text_mr: "EV मध्ये SOC चा अर्थ ?alse }, { en: "State of Charge", hi: "स्टेट ऑफ चार्ज", mr: "स्टेट ऑफ चार्ज", kn: "ಸ್ಟೇಟ್ ಆಫ್ ಚಾರ್ಜ್", te: "స్టేట్ ఆఫ్ ఛార్జ్", or: "ଷ୍ଟେଟ୍ ଅଫ୍ ଚାର୍ଜ", isCorrect: true }, { en: "Operation Control", hi: "सिस्टम ऑपरेशन कंट्रोल", mr: "सिस्टम ऑपरेशन कंट्रोल", kn: "ಆಪರೇಷನ್ ಕಂಟ್ರೋಲ್", te: "ఆపరేషన్ కంట్రోల్", or: "ଅପରେସନ୍ କଣ୍ଟ୍ରୋଲ୍", isCorrect: false }, { en: "Safety Component", hi: "सेफ्टी ऑफ कॉम्पोनेंट", mr: "सेफ्टी ऑफ कॉम्पोनेंट", kn: "ಸೇಫ್ಟಿ ಕಾಂಪೊನೆಂಟ್", te: "సేఫ్టీ కాంపోనెంట్", or: "ସେଫ୍ଟି କମ୍ପୋନେଣ୍ଟ", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "Where is the hub motor located?", question_text_hi: "EV स्कूटर में हब मोटर कहाँ लगी होती है?", question_text_mr: "EV स्कूटरमध्ये हब मोटर कोठे असते?", question_text_kn: "ಹಬ್ ಮೋಟಾರ್ ಎಲ್ಲಿದೆ?", question_text_te: "హబ్ మోటార్ ఎక్కడ ఉంటుంది?", question_text_or: "ହବ୍ ମୋଟର କେଉଁଠାରେ ଥାଏ?", options: [{ en: "Under seat", hi: "सीट के नीचे", mr: "सीट खाली", kn: "ಸೀಟಿನ ಅಡಿಯಲ್ಲಿ", te: "సీటు కింద", or: "ସିଟ୍ ତଳେ", isCorrect: false }, { en: "Inside wheel", hi: "पहिये के अंदर", mr: "चाकाच्या आत", kn: "ಚಕ್ರದ ಒಳಗೆ", te: "చక్రం లోపల", or: "ଚକ ଭିତରେ", isCorrect: true }, { en: "In handle", hi: "हैंडल में", mr: "हँडलमध्ये", kn: "ಹ್ಯಾಂಡಲ್ನಲ್ಲಿ", te: "హ్యాండిల్లో", or: "ହ୍ୟାଣ୍ଡେଲରେ", isCorrect: false }, { en: "Near battery", hi: "बैटरी के पास", mr: "बॅटरीजवळ", kn: "ಬ್ಯಾಟರಿ ಹತ್ತಿರ", te: "బ్యాటరీ దగ్గర", or: "ବ୍ୟାଟେରୀ ପାଖରେ", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "Why AC input and DC output in charger?", question_text_hi: "चार्जर में इनपुट AC और आउटपुट DC क्यों होता है?", question_text_mr: "चार्जरमध्ये AC इनपुट आणि DC आउटपुट का असते?", question_text_kn: "ಚಾರ್ಜರ್ನಲ್ಲಿ ಏಕೆ AC ಮತ್ತು DC ಇರುತ್ತದೆ?", question_text_te: "ఛార్జర్లో AC ఇన్పుట్ మరియు DC అవుట్పుట్ ఎందుకు ఉంటుంది?", question_text_or: "ଚାର୍ଜରରେ କାହିଁକି AC ଏବଂ DC ଥାଏ?", options: [{ en: "Battery charges on AC", hi: "बैटरी AC पर चार्ज होती है", mr: "बॅटरी AC वर चार्ज होते", kn: "ಬ್ಯಾಟರಿ AC ಯಲ್ಲಿ ಚಾರ್ಜ್ ಆಗುತ್ತದೆ", te: "బ్యాటరీ AC పై ఛార్జ్ అవుతుంది", or: "ବ୍ୟାଟେରୀ AC ରେ ଚାର୍ଜ ହୁଏ", isCorrect: false }, { en: "Battery stores DC", hi: "बैटरी DC पर स्टोर करती है", mr: "बॅटरी DC साठवते", kn: "ಬ್ಯಾಟರಿ DC ಯನ್ನು ಸಂಗ್ರಹಿಸುತ್ತದೆ", te: "బ్యాటరీ DC ని స్టోర్ చేస్తుంది", or: "ବ୍ୟାଟେରୀ DC ଷ୍ଟୋର୍ କରେ", isCorrect: true }, { en: "Motor runs on AC", hi: "मोटर AC पर चलती है", mr: "मोटार AC वर चालते", kn: "ಮೋಟಾರ್ AC ಯಲ್ಲಿ ಚಲಿಸುತ್ತದೆ", te: "మోటారు AC పై నడుస్తుంది", or: "ମୋଟର AC ରେ ଚାଲେ", isCorrect: false }, { en: "No reason", hi: "कोई खास कारण नहीं", mr: "काही कारण नाही", kn: "ಯಾವುದೇ ಕಾರಣವಿಲ್ಲ", te: "కారణం లేదు", or: "କୌଣସି କାରଣ ନାହିଁ", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What is cell balancing?", question_text_hi: "बैटरी सेल बैलेंसिंग का क्या मतलब है?", question_text_mr: "बॅटरी सेल बॅलन्सिंग म्हणजे काय?", question_text_kn: "ಸೆಲ್ ಬ್ಯಾಲೆನ್ಸಿಂಗ್ ಎಂದರೇನು?", question_text_te: "సెల్ బ్యాలెన్సింగ్ అంటే ఏమిటి?", question_text_or: "ସେଲ୍ ବାଲାନ୍ସିଂ କଣ?", options: [{ en: "Equal voltage", hi: "सभी सेल्स का समान वोल्टेज बनाए रखना", mr: "समान व्होल्टेज", kn: "ಸಮಾನ ವೋಲ್ಟೇಜ್", te: "సమాన వోల్టేజీ", or: "ସମାନ ଭୋଲ୍ଟେଜ୍", isCorrect: true }, { en: "Replacing cells", hi: "सेल्स को बदलना", mr: "सेल्स बदलणे", kn: "ಸೆಲ್ ಬದಲಾವಣೆ", te: "సెల్స్ మార్చడం", or: "ସେଲ୍ ବଦଳାଇବା", isCorrect: false }, { en: "Cooling", hi: "बैटरी को ठंडा करना", mr: "थंड करणे", kn: "ತಂಪಾಗಿಸುವುದು", te: "చల్లబరచడం", or: "ଥଣ୍ଡା କରିବା", isCorrect: false }, { en: "Heating", hi: "सेल्स को गर्म करना", mr: "गरम करणे", kn: "ಬಿಸಿ ಮಾಡುವುದು", te: "వేడి చేయడం", or: "ଗରମ କରିବା", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What is in a powertrain?", question_text_hi: "EV में पावर ट्रेन में क्या शामिल है?", question_text_mr: "पॉवर ट्रेनमध्ये काय असते?", question_text_kn: "ಪವರ್ಟ್ರೇನ್ನಲ್ಲಿ ಏನಿದೆ?", question_text_te: "పవర్ట్రైన్లో ఏముంటుంది?", question_text_or: "ପାୱାରଟ୍ରେନରେ କଣ ଥାଏ?", options: [{ en: "Only battery", hi: "केवल बैटरी", mr: "फक्त बॅटरी", kn: "ಕೇವಲ ಬ್ಯಾಟರಿ", te: "కేవలం బ్యాటరీ", or: "କେବଳ ବ୍ୟାଟେରୀ", isCorrect: false }, { en: "Motor, controller, battery", hi: "मोटर, कंट्रोलर, और बैटरी", mr: "मोटार, कंट्रोलर, बॅटरी", kn: "ಮೋಟಾರ್, ಕಂಟ್ರೋಲರ್, ಬ್ಯಾಟರಿ", te: "మోటారు, కంట్రోలర్, బ్యాటరీ", or: "ମୋଟର, କଣ୍ଟ୍ରୋଲର, ବ୍ୟାଟେରୀ", isCorrect: true }, { en: "Only tires", hi: "केवल टायर", mr: "फक्त टायर", kn: "ಕೇವಲ ಟೈರ್", te: "కేవలం టైర్లు", or: "କେବଳ ଟାୟାର", isCorrect: false }, { en: "Only charger", hi: "केवल चार्जर", mr: "फक्त चार्जर", kn: "ಕೇವಲ ಚಾರ್ಜರ್", te: "కేవలం ఛార్జర్", or: "କେବଳ ଚାର୍ଜର", isCorrect: false }], points: 1, difficulty: "easy" },
  { role: "technician", step: 1, question_text_en: "Proper battery temp?", question_text_hi: "EV बैटरी को कितने डिग्री तापमान पर रखना उचित है?", question_text_mr: "योग्य बॅटरी तापमान?", question_text_kn: "ಸೂಕ್ತ ಬ್ಯಾಟರಿ ತಾಪಮಾನ?", question_text_te: "సరైన బ్యాటరీ ఉష్ణోగ్రత?", question_text_or: "ସଠିକ୍ ବ୍ୟାଟେରୀ ତାପମାତ୍ରା?", options: [{ en: "0-10C", hi: "0-10C", mr: "0-10C", kn: "0-10C", te: "0-10C", or: "0-10C", isCorrect: false }, { en: "15-35C", hi: "15-35C", mr: "15-35C", kn: "15-35C", te: "15-35C", or: "15-35C", isCorrect: true }, { en: "50-60C", hi: "50-60C", mr: "50-60C", kn: "50-60C", te: "50-60C", or: "50-60C", isCorrect: false }, { en: "70-80C", hi: "70-80C", mr: "70-80C", kn: "70-80C", te: "70-80C", or: "70-80C", isCorrect: false }], points: 1, difficulty: "medium" },
  { role: "technician", step: 1, question_text_en: "What does throttle do?", question_text_hi: "EV में थ्रॉटल क्या करता है?", question_text_mr: "थ्रॉटल काय करते?", question_text_kn: "ಥ್ರೊಟಲ್ ಏನು ಮಾಡುತ್ತದೆ?", question_text_te: "థొరెటల్ ఏమి చేస్తుంది?", question_text_or: "ଥ୍ରୋଟଲ୍ କଣ କରେ?", options: [{ en: "Brakes", hi: "ब्रेक लगाता है", mr: "ब्रेक लावणे", kn: "ಬ್ರೇಕ್", te: "బ్రేకులు", or: "ବ୍ରେକ୍", isCorrect: false }, { en: "Controls speed", hi: "गति नियंत्रित करता है", mr: "वेग नियंत्रित करणे", kn: "ವೇಗ ನಿಯಂತ್ರಣ", te: "వేగ నియంత్రణ", or: "ଗତି ନିୟନ୍ତ୍ରଣ", isCorrect: true }, { en: "Charges", hi: "बैटरी चार्ज करता है", mr: "चार्ज करणे", kn: "ಚಾರ್ಜ್", te: "ఛార్జింగ్", or: "ଚାର୍ଜିଂ", isCorrect: false }, { en: "Lights", hi: "लाइट जलाता है", mr: "लाईट लावणे", kn: "ಲೈಟ್", te: "లైట్లు", or: "ଲାଇଟ୍", isCorrect: false }], points: 1, difficulty: "easy" },
];

console.log("Total questions to migrate:", allQuestions.length);
console.log("Starting migration...");

async function migrate() {
  try {
    await sql\`DELETE FROM verification_questions\`;
    console.log("Cleared old questions");
    
    for (const q of allQuestions) {
      await sql\`INSERT INTO verification_questions (role, step, question_text_en, question_text_hi, question_text_mr, question_text_kn, question_text_te, question_text_or, options, points, difficulty) VALUES (\${q.role}, \${q.step}, \${q.question_text_en}, \${q.question_text_hi}, \${q.question_text_mr}, \${q.question_text_kn}, \${q.question_text_te}, \${q.question_text_or}, \${JSON.stringify(q.options)}::jsonb, \${q.points}, \${q.difficulty})\`;
    }
    
    const count = await sql\`SELECT COUNT(*) FROM verification_questions\`;
    console.log("Migration complete! Total:", count[0].count);
  } catch(e) {
    console.error("Error:", e);
  }
}

migrate();
