#!/usr/bin/env node

/**
 * Database Migration Script - Verification Questions & Card Orders
 */

require('dotenv').config();
const { neon } = require('@neondatabase/serverless');

const DATABASE_URL = process.env.EXPO_PUBLIC_DATABASE_URL;

if (!DATABASE_URL) {
    console.error('❌ Error: EXPO_PUBLIC_DATABASE_URL not found in .env file');
    process.exit(1);
}

const sql = neon(DATABASE_URL);

// Full Question Bank (50 Questions)
const questions = [
    // === EV TECHNICIAN STEP 1 (15 questions) ===
    { role: 'technician', step: 1, question_text_en: 'Which cell technology is most commonly used in EV batteries?', question_text_hi: 'EV बैटरी में सबसे सामान्य रूप से कौन सी सेल तकनीक उपयोग की जाती है?', options: JSON.stringify([{ en: 'Lead-Acid', hi: 'लीड-एसिड', isCorrect: false }, { en: 'Lithium-Ion', hi: 'लिथियम-आयन', isCorrect: true }, { en: 'Nickel-Cadmium', hi: 'निकल-कैडमियम', isCorrect: false }, { en: 'Zinc-Carbon', hi: 'जिंक-कार्बन', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'What is the full form of BMS?', question_text_hi: 'BMS का पूरा नाम क्या है?', options: JSON.stringify([{ en: 'Battery Monitoring System', hi: 'बैटरी मॉनिटरिंग सिस्टम', isCorrect: false }, { en: 'Battery Management System', hi: 'बैटरी मैनेजमेंट सिस्टम', isCorrect: true }, { en: 'Basic Motor System', hi: 'बेसिक मोटर सिस्टम', isCorrect: false }, { en: 'Balanced Mode System', hi: 'बैलेंस्ड मोड सिस्टम', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'What does BLDC motor mean in EV?', question_text_hi: 'EV में BLDC मोटर का क्या अर्थ है?', options: JSON.stringify([{ en: 'Brushed Direct Current', hi: 'ब्रश्ड डायरेक्ट करंट', isCorrect: false }, { en: 'Brushless Direct Current', hi: 'ब्रशलेस डायरेक्ट करंट', isCorrect: true }, { en: 'Basic Low Drive Current', hi: 'बेसिक लो ड्राइव करंट', isCorrect: false }, { en: 'Balanced Load Distribution Current', hi: 'बैलेंस्ड लोड डिस्ट्रीब्यूशन करंट', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'What is the function of regenerative braking?', question_text_hi: 'रीजनरेटिव ब्रेकिंग का क्या काम है?', options: JSON.stringify([{ en: 'Increase speed', hi: 'गति बढ़ाना', isCorrect: false }, { en: 'Send energy back to battery during braking', hi: 'ब्रेकिंग के दौरान ऊर्जा वापस बैटरी में भेजना', isCorrect: true }, { en: 'Increase tire grip', hi: 'टायर की पकड़ बढ़ाना', isCorrect: false }, { en: 'Cool down the motor', hi: 'मोटर को ठंडा करना', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'In what unit is EV battery capacity measured?', question_text_hi: 'EV बैटरी की क्षमता किसमें मापी जाती है?', options: JSON.stringify([{ en: 'Watt (W)', hi: 'वाट (W)', isCorrect: false }, { en: 'Kilowatt-hour (kWh)', hi: 'किलोवाट-ऑवर (kWh)', isCorrect: true }, { en: 'Ampere (A)', hi: 'एम्पियर (A)', isCorrect: false }, { en: 'Volt (V)', hi: 'वोल्ट (V)', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'What is thermal runaway?', question_text_hi: 'थर्मल रनवे क्या है?', options: JSON.stringify([{ en: 'Normal temperature of battery', hi: 'बैटरी का सामान्य तापमान', isCorrect: false }, { en: 'Uncontrolled rise in heat in battery', hi: 'बैटरी में अनियंत्रित गर्मी का बढ़ना', isCorrect: true }, { en: 'Motor cooling', hi: 'मोटर का ठंडा होना', isCorrect: false }, { en: 'Normal charging process', hi: 'चार्जिंग की सामान्य प्रक्रिया', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What is the function of controller in EV?', question_text_hi: 'EV में कंट्रोलर का क्या काम है?', options: JSON.stringify([{ en: 'Charge the battery', hi: 'बैटरी चार्ज करना', isCorrect: false }, { en: 'Control motor speed and torque', hi: 'मोटर की गति और टॉर्क नियंत्रित करना', isCorrect: true }, { en: 'Change tires', hi: 'टायर बदलना', isCorrect: false }, { en: 'Fill fuel', hi: 'ईंधन भरना', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What is the use of DC-DC converter?', question_text_hi: 'DC-DC कनवर्टर का क्या उपयोग है?', options: JSON.stringify([{ en: 'Convert high voltage to low voltage', hi: 'उच्च वोल्टेज को निम्न वोल्टेज में बदलना', isCorrect: true }, { en: 'Convert AC to DC', hi: 'AC को DC में बदलना', isCorrect: false }, { en: 'Increase motor speed', hi: 'मोटर की गति बढ़ाना', isCorrect: false }, { en: 'Cool the battery', hi: 'बैटरी को ठंडा करना', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What does SOC mean in EV?', question_text_hi: 'EV में सोक (SOC) का क्या अर्थ है?', options: JSON.stringify([{ en: 'Speed of Charging', hi: 'स्पीड ऑफ चार्जिंग', isCorrect: false }, { en: 'State of Charge', hi: 'स्टेट ऑफ चार्ज', isCorrect: true }, { en: 'System Operation Control', hi: 'सिस्टम ऑपरेशन कंट्रोल', isCorrect: false }, { en: 'Safety of Component', hi: 'सेफ्टी ऑफ कॉम्पोनेंट', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'Where is the hub motor located in an EV scooter?', question_text_hi: 'EV स्कूटर में हब मोटर कहाँ लगी होती है?', options: JSON.stringify([{ en: 'Under the seat', hi: 'सीट के नीचे', isCorrect: false }, { en: 'Inside the wheel', hi: 'पहिये के अंदर', isCorrect: true }, { en: 'In the handle', hi: 'हैंडल में', isCorrect: false }, { en: 'Near the battery', hi: 'बैटरी के पास', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'Why does a charger have AC input and DC output?', question_text_hi: 'चार्जर में इनपुट AC और आउटपुट DC क्यों होता है?', options: JSON.stringify([{ en: 'Battery charges on AC', hi: 'बैटरी AC पर चार्ज होती है', isCorrect: false }, { en: 'Battery stores on DC', hi: 'बैटरी DC पर स्टोर करती है', isCorrect: true }, { en: 'Motor runs on AC', hi: 'मोटर AC पर चलती है', isCorrect: false }, { en: 'No specific reason', hi: 'कोई खास कारण नहीं', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What does battery cell balancing mean?', question_text_hi: 'बैटरी सेल बैलेंसिंग का क्या मतलब है?', options: JSON.stringify([{ en: 'Maintaining equal voltage of all cells', hi: 'सभी सेल्स का समान वोल्टेज बनाए रखना', isCorrect: true }, { en: 'Replacing cells', hi: 'सेल्स को बदलना', isCorrect: false }, { en: 'Cooling the battery', hi: 'बैटरी को ठंडा करना', isCorrect: false }, { en: 'Heating the cells', hi: 'सेल्स को गर्म करना', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What is included in the powertrain of an EV?', question_text_hi: 'EV में पावर ट्रेन में क्या शामिल है?', options: JSON.stringify([{ en: 'Only battery', hi: 'केवल बैटरी', isCorrect: false }, { en: 'Motor, controller, and battery', hi: 'मोटर, कंट्रोलर, और बैटरी', isCorrect: true }, { en: 'Only tires', hi: 'केवल टायर', isCorrect: false }, { en: 'Only charger', hi: 'केवल चार्जर', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 1, question_text_en: 'At what temperature should an EV battery be kept?', question_text_hi: 'EV बैटरी को कितने डिग्री तापमान पर रखना उचित है?', options: JSON.stringify([{ en: '0-10°C', hi: '0-10°C', isCorrect: false }, { en: '15-35°C', hi: '15-35°C', isCorrect: true }, { en: '50-60°C', hi: '50-60°C', isCorrect: false }, { en: '70-80°C', hi: '70-80°C', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 1, question_text_en: 'What does the throttle do in an EV?', question_text_hi: 'EV में थ्रॉटल क्या करता है?', options: JSON.stringify([{ en: 'Applies brakes', hi: 'ब्रेक लगाता है', isCorrect: false }, { en: 'Controls speed', hi: 'गति नियंत्रित करता है', isCorrect: true }, { en: 'Charges battery', hi: 'बैटरी चार्ज करता है', isCorrect: false }, { en: 'Turns on lights', hi: 'लाइट जलाता है', isCorrect: false }]), points: 1, difficulty: 'easy' },

    // === EV TECHNICIAN STEP 2 (15 questions) ===
    { role: 'technician', step: 2, question_text_en: 'How do you measure battery voltage with a multimeter?', question_text_hi: 'मल्टीमीटर से बैटरी वोल्टेज कैसे मापते हैं?', options: JSON.stringify([{ en: 'On AC mode', hi: 'AC मोड पर', isCorrect: false }, { en: 'On DC voltage mode', hi: 'DC वोल्टेज मोड पर', isCorrect: true }, { en: 'On resistance mode', hi: 'रेजिस्टेंस मोड पर', isCorrect: false }, { en: 'On current mode', hi: 'करंट मोड पर', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 2, question_text_en: 'How to detect a short circuit in battery?', question_text_hi: 'बैटरी में शॉर्ट सर्किट का पता कैसे लगाएं?', options: JSON.stringify([{ en: 'Battery will heat and voltage will drop', hi: 'बैटरी गर्म होगी और वोल्टेज गिरेगा', isCorrect: true }, { en: 'Battery will remain cold', hi: 'बैटरी ठंडी रहेगी', isCorrect: false }, { en: 'Voltage will increase', hi: 'वोल्टेज बढ़ेगा', isCorrect: false }, { en: 'No change', hi: 'कोई बदलाव नहीं', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What to check first if motor makes noise?', question_text_hi: 'मोटर में कोई आवाज़ आए तो पहले क्या चेक करें?', options: JSON.stringify([{ en: 'Battery', hi: 'बैटरी', isCorrect: false }, { en: 'Bearing and connections', hi: 'बेयरिंग और कनेक्शन', isCorrect: true }, { en: 'Tires', hi: 'टायर', isCorrect: false }, { en: 'Seat', hi: 'सीट', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What are the symptoms of controller failure?', question_text_hi: 'कंट्रोलर फेल होने के लक्षण क्या हैं?', options: JSON.stringify([{ en: 'Motor won\'t start or runs intermittently', hi: 'मोटर स्टार्ट नहीं होगा या रुक- रुक कर चलेगा', isCorrect: true }, { en: 'Battery charges fast', hi: 'बैटरी जल्दी चार्ज होगी', isCorrect: false }, { en: 'Lights get brighter', hi: 'लाइट तेज होगी', isCorrect: false }, { en: 'Horn sounds louder', hi: 'हॉर्न जोर से बजेगा', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'Charger green light not on, what could be the reason?', question_text_hi: 'चार्जर का ग्रीन लाइट नहीं जल रही, क्या कारण हो सकता है?', options: JSON.stringify([{ en: 'Charger faulty or battery not full', hi: 'चार्जर खराब या बैटरी फुल नहीं हुई', isCorrect: true }, { en: 'Problem in motor', hi: 'मोटर में समस्या', isCorrect: false }, { en: 'Tire puncture', hi: 'टायर पंचर', isCorrect: false }, { en: 'Brake problem', hi: 'ब्रेक की समस्या', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What to do when BMS error occurs?', question_text_hi: 'BMS एरर आने पर क्या करें?', options: JSON.stringify([{ en: 'Disconnect battery and reset BMS', hi: 'बैटरी को डिस्कनेक्ट करके BMS रीसेट करें', isCorrect: true }, { en: 'Replace motor', hi: 'मोटर बदलें', isCorrect: false }, { en: 'Change tires', hi: 'टायर बदलें', isCorrect: false }, { en: 'Do nothing', hi: 'कुछ न करें', isCorrect: false }]), points: 1, difficulty: 'hard' },
    { role: 'technician', step: 2, question_text_en: 'What to check first if scooter suddenly stops?', question_text_hi: 'स्कूटर अचानक बंद हो जाए तो पहले क्या चेक करें?', options: JSON.stringify([{ en: 'Battery connection and fuse', hi: 'बैटरी कनेक्शन और फ्यूज', isCorrect: true }, { en: 'Seat', hi: 'सीट', isCorrect: false }, { en: 'Mirror', hi: 'मिरर', isCorrect: false }, { en: 'Body panel', hi: 'बॉडी पैनल', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'technician', step: 2, question_text_en: 'What is the function of three wires (U, V, W) in motor?', question_text_hi: 'मोटर में तीन वायर (U, V, W) का क्या काम है?', options: JSON.stringify([{ en: 'Battery charging', hi: 'बैटरी चार्जिंग', isCorrect: false }, { en: 'Three-phase power supply', hi: 'थ्री-फेज पावर सप्लाई', isCorrect: true }, { en: 'Lighting', hi: 'लाइटिंग', isCorrect: false }, { en: 'Horn connection', hi: 'हॉर्न कनेक्शन', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What is the function of hall sensor?', question_text_hi: 'हॉल सेंसर का क्या काम है?', options: JSON.stringify([{ en: 'Measure battery temperature', hi: 'बैटरी तापमान नापना', isCorrect: false }, { en: 'Indicate motor position', hi: 'मोटर की पोजीशन बताना', isCorrect: true }, { en: 'Measure speed', hi: 'स्पीड मापना', isCorrect: false }, { en: 'Light control', hi: 'लाइट कंट्रोल', isCorrect: false }]), points: 1, difficulty: 'hard' },
    { role: 'technician', step: 2, question_text_en: 'What happens if one cell in battery pack is faulty?', question_text_hi: 'बैटरी पैक में एक सेल खराब हो तो क्या होगा?', options: JSON.stringify([{ en: 'Entire battery will be affected', hi: 'पूरी बैटरी प्रभावित होगी', isCorrect: true }, { en: 'No effect', hi: 'कोई असर नहीं', isCorrect: false }, { en: 'Motor runs faster', hi: 'मोटर तेज चलेगी', isCorrect: false }, { en: 'Lights get brighter', hi: 'लाइट तेज होगी', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'Why is insulation resistance test done?', question_text_hi: 'इन्सुलेशन रेजिस्टेंस टेस्ट क्यों किया जाता है?', options: JSON.stringify([{ en: 'To check current leakage', hi: 'करंट लीकेज चेक करने के लिए', isCorrect: true }, { en: 'To charge battery', hi: 'बैटरी चार्ज करने के लिए', isCorrect: false }, { en: 'To increase motor speed', hi: 'मोटर स्पीड बढ़ाने के लिए', isCorrect: false }, { en: 'To check tire pressure', hi: 'टायर प्रेशर चेक करने के लिए', isCorrect: false }]), points: 1, difficulty: 'hard' },
    { role: 'technician', step: 2, question_text_en: 'What does IP rating for waterproofing indicate in EV?', question_text_hi: 'EV में वॉटरप्रूफिंग का IP रेटिंग क्या दर्शाती है?', options: JSON.stringify([{ en: 'Level of protection from dust and water', hi: 'धूल और पानी से सुरक्षा का स्तर', isCorrect: true }, { en: 'Battery capacity', hi: 'बैटरी क्षमता', isCorrect: false }, { en: 'Motor power', hi: 'मोटर पावर', isCorrect: false }, { en: 'Speed limit', hi: 'स्पीड लिमिट', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What SOC should be maintained when storing lithium battery?', question_text_hi: 'लिथियम बैटरी को स्टोर करते समय SOC कितनी रखनी चाहिए?', options: JSON.stringify([{ en: '100%', hi: '100%', isCorrect: false }, { en: '40-60%', hi: '40-60%', isCorrect: true }, { en: '0%', hi: '0%', isCorrect: false }, { en: '10%', hi: '10%', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'technician', step: 2, question_text_en: 'What to check if regenerative braking is not working?', question_text_hi: 'रीजनरेटिव ब्रेकिंग काम न करे तो क्या चेक करें?', options: JSON.stringify([{ en: 'Controller settings and brake sensor', hi: 'कंट्रोलर सेटिंग्स और ब्रेक सेंसर', isCorrect: true }, { en: 'Tire pressure', hi: 'टायर प्रेशर', isCorrect: false }, { en: 'Seat position', hi: 'सीट पोजीशन', isCorrect: false }, { en: 'Mirror angle', hi: 'मिरर एंगल', isCorrect: false }]), points: 1, difficulty: 'hard' },
    { role: 'technician', step: 2, question_text_en: 'What is the function of CAN bus in EV?', question_text_hi: 'CAN बस का क्या काम है EV में?', options: JSON.stringify([{ en: 'Communication between different components', hi: 'विभिन्न कंपोनेंट्स के बीच कम्युनिकेशन', isCorrect: true }, { en: 'Battery charging', hi: 'बैटरी चार्जिंग', isCorrect: false }, { en: 'Motor cooling', hi: 'मोटर कूलिंग', isCorrect: false }, { en: 'Tire pressure monitoring', hi: 'टायर प्रेशर मॉनिटरिंग', isCorrect: false }]), points: 1, difficulty: 'hard' },

    // === SALES (10 questions) ===
    { role: 'sales', step: 1, question_text_en: 'What is the biggest saving for customers with EV?', question_text_hi: 'ग्राहक को EV की सबसे बड़ी बचत किस पर होती है?', options: JSON.stringify([{ en: 'Fuel/charging cost', hi: 'ईंधन/चार्जिंग लागत', isCorrect: true }, { en: 'Tires', hi: 'टायर', isCorrect: false }, { en: 'Insurance', hi: 'बीमा', isCorrect: false }, { en: 'Parking', hi: 'पार्किंग', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'What does range anxiety mean in EV?', question_text_hi: 'EV में रेंज एंग्जाइटी का क्या मतलब है?', options: JSON.stringify([{ en: 'Fear of battery running out', hi: 'बैटरी खत्म होने का डर', isCorrect: true }, { en: 'Fear of speed', hi: 'स्पीड का डर', isCorrect: false }, { en: 'Fear of price', hi: 'कीमत का डर', isCorrect: false }, { en: 'Fear of service', hi: 'सर्विस का डर', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'How does customer get subsidy on EV?', question_text_hi: 'ग्राहक EV पर सब्सिडी कैसे प्राप्त करता है?', options: JSON.stringify([{ en: 'Under FAME-II and state schemes', hi: 'FAME-II और राज्य योजनाओं के तहत', isCorrect: true }, { en: 'From petrol pump', hi: 'पेट्रोल पंप से', isCorrect: false }, { en: 'From insurance company', hi: 'बीमा कंपनी से', isCorrect: false }, { en: 'From toll plaza', hi: 'टोल प्लाजा से', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'sales', step: 1, question_text_en: 'What is the biggest concern for customers buying EV?', question_text_hi: 'EV खरीदने में ग्राहक की सबसे बड़ी चिंता क्या होती है?', options: JSON.stringify([{ en: 'Range and charging infrastructure', hi: 'रेंज और चार्जिंग इंफ्रास्ट्रक्चर', isCorrect: true }, { en: 'Color', hi: 'रंग', isCorrect: false }, { en: 'Seat cover', hi: 'सीट कवर', isCorrect: false }, { en: 'Horn', hi: 'हॉर्न', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'Why is EV TCO lower than petrol vehicle?', question_text_hi: 'EV की TCO (Total Cost of Ownership) पेट्रोल वाहन से कम क्यों है?', options: JSON.stringify([{ en: 'Lower charging and maintenance cost', hi: 'कम चार्जिंग और मेंटेनेंस लागत', isCorrect: true }, { en: 'Higher speed', hi: 'अधिक स्पीड', isCorrect: false }, { en: 'Larger size', hi: 'बड़ा साइज', isCorrect: false }, { en: 'More weight', hi: 'ज्यादा वजन', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'sales', step: 1, question_text_en: 'How many years is battery warranty usually?', question_text_hi: 'बैटरी वारंटी आमतौर पर कितने साल की होती है?', options: JSON.stringify([{ en: '1 year', hi: '1 साल', isCorrect: false }, { en: '3-5 years', hi: '3-5 साल', isCorrect: true }, { en: '10 years', hi: '10 साल', isCorrect: false }, { en: '6 months', hi: '6 महीने', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'What benefit of home charging will you tell customer?', question_text_hi: 'ग्राहक को होम चार्जिंग का क्या फायदा बताएंगे?', options: JSON.stringify([{ en: 'Charge at night, ready in morning', hi: 'रात में चार्ज, सुबह तैयार', isCorrect: true }, { en: 'Going to petrol pump', hi: 'पेट्रोल पंप जाना', isCorrect: false }, { en: 'Daily service', hi: 'हर दिन सर्विस', isCorrect: false }, { en: 'Standing in traffic', hi: 'ट्रैफिक में खड़ा रहना', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'How will you explain down payment and EMI for EV?', question_text_hi: 'EV में डाउन पेमेंट और EMI कैसे समझाएंगे?', options: JSON.stringify([{ en: 'On price after subsidy', hi: 'सब्सिडी के बाद की कीमत पर', isCorrect: true }, { en: 'Only on MRP', hi: 'केवल MRP पर', isCorrect: false }, { en: 'Without interest', hi: 'बिना ब्याज के', isCorrect: false }, { en: 'Only in cash', hi: 'केवल कैश में', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'sales', step: 1, question_text_en: 'Why is test ride important for customer?', question_text_hi: 'ग्राहक को टेस्ट राइड क्यों जरूरी है?', options: JSON.stringify([{ en: 'Ride experience and answers to questions', hi: 'राइड का अनुभव और सवालों का जवाब', isCorrect: true }, { en: 'To waste time', hi: 'समय बर्बाद करने के लिए', isCorrect: false }, { en: 'To save petrol expense', hi: 'पेट्रोल खर्च बचाने के लिए', isCorrect: false }, { en: 'To roam in showroom', hi: 'शोरूम में घूमने के लिए', isCorrect: false }]), points: 1, difficulty: 'easy' },
    { role: 'sales', step: 1, question_text_en: 'How will you answer customer objection "EV is expensive"?', question_text_hi: 'ग्राहक की आपत्ति "EV महंगी है" का जवाब क्या देंगे?', options: JSON.stringify([{ en: 'Show TCO comparison - savings in 3-5 years', hi: 'TCO तुलना दिखाएं - 3-5 साल में बचत', isCorrect: true }, { en: 'Yes, very expensive', hi: 'हां, बहुत महंगी है', isCorrect: false }, { en: 'Take petrol vehicle', hi: 'पेट्रोल गाड़ी लें', isCorrect: false }, { en: 'Say nothing', hi: 'कुछ न कहें', isCorrect: false }]), points: 1, difficulty: 'medium' },

    // === WORKSHOP (10 questions) ===
    { role: 'workshop', step: 1, question_text_en: 'To ensure the workshop is profitable, how should you distribute the daily workload among your technicians?', question_text_hi: 'वर्कशॉप को प्रॉफिटेबल बनाने के लिए, टेक्नीशियन के बीच डेली वर्कलोड कैसे बाँटना चाहिए?', options: JSON.stringify([{ en: 'Give the most work to the junior technicians so they can learn', hi: 'जूनियर टेक्नीशियन को सबसे ज्यादा काम दें ताकि वे सीख सकें', isCorrect: false }, { en: 'Assign jobs based on a Skill Matrix to reduce repeat complaints', hi: 'स्किल मैट्रिक्स के आधार पर जॉब असाइन करें ताकि रिपीट शिकायतें कम हों', isCorrect: true }, { en: 'Let the technicians choose their own jobs every morning', hi: 'हर सुबह टेक्नीशियन को अपनी जॉब खुद चुनने दें', isCorrect: false }, { en: 'Give every technician exactly the same number of vehicles', hi: 'हर टेक्नीशियन को वाहनों की एक समान संख्या दें', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'Why is it a Red Flag if a Workshop Manager does not close all Job Cards daily?', question_text_hi: 'अगर वर्कशॉप मैनेजर रोज़ सभी जॉब कार्ड बंद नहीं करता तो यह "रेड फ्लैग" क्यों है?', options: JSON.stringify([{ en: 'Because the computer might run out of storage space', hi: 'क्योंकि कंप्यूटर में स्टोरेज खत्म हो सकता है', isCorrect: false }, { en: 'It creates an Inventory Gap in spare parts and delays billing/revenue cycle', hi: 'यह स्पेयर पार्ट्स में इन्वेंटरी गैप बनाता है और बिलिंग/रेवेन्यू साइकिल में देरी करता है', isCorrect: true }, { en: 'Technicians don\'t like seeing open JCs on the screen', hi: 'टेक्नीशियन को स्क्रीन पर ओपन जॉब कार्ड देखना पसंद नहीं', isCorrect: false }, { en: 'It makes the workshop look messy', hi: 'इससे वर्कशॉप गंदा दिखता है', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'If a customer gives a Detractor score (0-6) on an NPS survey, what is the most professional first step?', question_text_hi: 'अगर ग्राहक NPS सर्वे में "डिट्रैक्टर" स्कोर (0-6) देता है, तो सबसे प्रोफेशनल पहला कदम क्या है?', options: JSON.stringify([{ en: 'Ignore it; some customers are never happy', hi: 'इग्नोर करें; कुछ ग्राहक कभी खुश नहीं होते', isCorrect: false }, { en: 'Call the customer and argue that the rating is unfair', hi: 'ग्राहक को कॉल करें और तर्क दें कि रेटिंग अनफेयर है', isCorrect: false }, { en: 'Call the customer within 24 hours to Listen, Apologize, and Resolve', hi: '24 घंटे के अंदर कॉल करें, Listen, Apologize, and Resolve करें', isCorrect: true }, { en: 'Give the customer a 50% discount on their next service immediately', hi: 'बिना सवाल पूछे अगली सर्विस पर 50% डिस्काउंट दें', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'What is the most effective way to ensure a customer comes back for their next service?', question_text_hi: 'अगली सर्विस के लिए ग्राहक को वापस लाने का सबसे प्रभावी तरीका क्या है?', options: JSON.stringify([{ en: 'Having a big TV in the waiting lounge', hi: 'वेटिंग लाउंज में बड़ा टीवी लगाना', isCorrect: false }, { en: 'PSF (Post-Service Follow-up) calls within 3 days', hi: 'सर्विस के 3 दिनों के अंदर PSF कॉल करके वाहन की स्थिति चेक करना', isCorrect: true }, { en: 'Sending them 5 SMS per day about new bike offers', hi: 'हर दिन 5 SMS नए बाइक ऑफर के बारे में भेजना', isCorrect: false }, { en: 'Offering the cheapest service price in the city', hi: 'शहर में सबसे सस्ती सर्विस प्राइस ऑफर करना', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'What is the industry-standard Lead Time to acknowledge a high-priority customer complaint?', question_text_hi: 'हाई-प्रायोरिटी ग्राहक शिकायत को स्वीकार करने का इंडस्ट्री-स्टैंडर्ड "लीड टाइम" क्या है?', options: JSON.stringify([{ en: '1 week', hi: '1 हफ्ता', isCorrect: false }, { en: '1 to 4 Hours (Immediate acknowledgement is key)', hi: '1 से 4 घंटे (तुरंत स्वीकार करना गुस्से को कम करने की कुंजी है)', isCorrect: true }, { en: '48 Hours', hi: '48 घंटे', isCorrect: false }, { en: 'Only when the customer visits the workshop in person', hi: 'तब तक जब तक ग्राहक खुद वर्कशॉप में न आए', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'If your workshop has 4 bays and 4 technicians, what is a healthy Average Vehicle Intake per day?', question_text_hi: 'अगर 4 बे और 4 टेक्नीशियन हैं, तो स्टैंडर्ड मेंटेनेंस के लिए प्रति दिन हेल्दी "एवरेज व्हीकल इनटेक" कितना होना चाहिए?', options: JSON.stringify([{ en: '2 vehicles total (takes too long)', hi: 'कुल 2 वाहन (बहुत लंबा समय लगता है)', isCorrect: false }, { en: '12 to 16 vehicles (3–4 vehicles per bay per day)', hi: '12 से 16 वाहन (प्रति बे प्रति दिन 3–4 वाहन मानकर)', isCorrect: true }, { en: '50 vehicles (leads to poor quality)', hi: '50 वाहन (क्वालिटी खराब होगी)', isCorrect: false }, { en: 'It doesn\'t matter as long as the technicians are busy', hi: 'कोई फर्क नहीं पड़ता जब तक टेक्नीशियन व्यस्त हैं', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'What is the risk if you simply Close a Detractor case without talking to them?', question_text_hi: 'ग्राहक ने NPS स्कोर 3 दिया लेकिन रिकवरी कॉल नहीं उठाया। बिना बात किए केस क्लोज करने का क्या रिस्क है?', options: JSON.stringify([{ en: 'No risk; you tried your best', hi: 'कोई रिस्क नहीं; आपने कोशिश की', isCorrect: false }, { en: 'The customer will probably forget the issue', hi: 'ग्राहक शायद मुद्दा भूल जाएगा', isCorrect: false }, { en: 'High Risk: Unresolved Detractor will likely escalate to Social Media or Legal Complaint', hi: 'हाई रिस्क: अनरिजॉल्व्ड डिट्रैक्टर सोशल मीडिया या लीगल कम्प्लेंट में बदल सकता है', isCorrect: true }, { en: 'The NPS score will automatically become a 9 (Promoter) after 48 hours', hi: '48 घंटे बाद NPS स्कोर ऑटोमैटिक 9 हो जाएगा', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'How do you handle a Mandatory Field Fix for a specific batch of VINs?', question_text_hi: 'OEM ने स्पेसिफिक VINs बैच के लिए Mandatory Field Fix जारी किया है। VIN लिस्ट कैसे हैंडल करें?', options: JSON.stringify([{ en: 'Mark the VINs as Completed now and fix them later', hi: 'VINs को अभी Completed मार्क करें और बाद में फिक्स करें', isCorrect: false }, { en: 'Call those specific VIN owners immediately and ensure physical part is replaced and photographed', hi: 'उन VIN ओनर्स को तुरंत कॉल करें और पार्ट बदलकर फोटो के साथ क्लोज करें', isCorrect: true }, { en: 'Only fix the bikes that belong to VIP customers', hi: 'केवल VIP कस्टमर्स की बाइक्स फिक्स करें', isCorrect: false }, { en: 'Wait for the OEM to send a reminder', hi: 'OEM से रिमाइंडर आने तक इंतजार करें', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'Where is the most effective place to find Ready-to-Work EV Technicians?', question_text_hi: 'नए सर्विस सेंटर के लिए Ready-to-Work EV टेक्नीशियन ढूंढने का सबसे प्रभावी जगह क्या है?', options: JSON.stringify([{ en: 'Post a Hiring banner outside the local petrol pump', hi: 'लोकल पेट्रोल पंप के बाहर Hiring बैनर लगाएं', isCorrect: false }, { en: 'Use the Everified app to filter candidates who have already passed EV tests', hi: 'Everified ऐप यूज करें जो पहले से EV टेस्ट पास कर चुके कैंडिडेट्स को फिल्टर करे', isCorrect: true }, { en: 'Visit a local college and hire freshers who have never seen an EV motor', hi: 'लोकल कॉलेज जाएं और फ्रेशर्स हायर करें जिन्होंने कभी EV मोटर नहीं देखा', isCorrect: false }, { en: 'Wait for people to send their CVs to your email', hi: 'ईमेल पर CV आने का इंतजार करें', isCorrect: false }]), points: 1, difficulty: 'medium' },
    { role: 'workshop', step: 1, question_text_en: 'What is the most sustainable way to increase service volume at 50% capacity?', question_text_hi: 'वर्कशॉप अभी 50% कैपेसिटी पर चल रही है। सर्विस वॉल्यूम बढ़ाने का सबसे सस्टेनेबल तरीका क्या है?', options: JSON.stringify([{ en: 'Ask technicians to stand outside and wave at EV riders', hi: 'टेक्नीशियन को बाहर खड़े करके EV राइडर्स को बुलाने को कहें', isCorrect: false }, { en: 'Run a Battery Health Clinic campaign calling existing customers for free diagnostic checkup', hi: 'Battery Health Clinic कैंपेन चलाएं, मौजूदा कस्टमर्स को फ्री डायग्नोस्टिक चेकअप के लिए कॉल करें', isCorrect: true }, { en: 'Reduce the service quality so the bikes break down faster', hi: 'सर्विस क्वालिटी कम करें ताकि बाइक्स जल्दी खराब हों', isCorrect: false }, { en: 'Fire half the technicians to save money', hi: 'आधे टेक्नीशियन निकाल दें ताकि पैसे बचें', isCorrect: false }]), points: 1, difficulty: 'medium' },
];

async function migrate() {
    console.log('🚀 Starting verification questions migration...\n');

    try {
        // Create verification_questions table
        console.log('📝 Creating verification_questions table...');
        await sql`
            CREATE TABLE IF NOT EXISTS verification_questions (
                id SERIAL PRIMARY KEY,
                role VARCHAR(50) NOT NULL,
                step INTEGER NOT NULL DEFAULT 1,
                question_text_en TEXT NOT NULL,
                question_text_hi TEXT NOT NULL,
                question_text_mr TEXT,
                question_text_kn TEXT,
                question_text_te TEXT,
                question_text_or TEXT,
                options JSONB NOT NULL,
                points INTEGER DEFAULT 1,
                difficulty VARCHAR(20) DEFAULT 'medium',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        `;
        console.log('✅ verification_questions table created\n');

        // Create card_orders table
        console.log('📝 Creating card_orders table...');
        await sql`
            CREATE TABLE IF NOT EXISTS card_orders (
                id SERIAL PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                full_name VARCHAR(255) NOT NULL,
                address TEXT NOT NULL,
                city VARCHAR(100) NOT NULL,
                pincode VARCHAR(10) NOT NULL,
                mobile VARCHAR(15) NOT NULL,
                status VARCHAR(50) DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        `;
        console.log('✅ card_orders table created\n');

        // Clear existing questions
        console.log('🗑️ Clearing existing questions...');
        await sql`DELETE FROM verification_questions`;

        // Insert questions
        console.log('📝 Inserting verification questions...');
        for (const q of questions) {
            await sql`
                INSERT INTO verification_questions (
                    role, step, question_text_en, question_text_hi, 
                    question_text_mr, question_text_kn, question_text_te, question_text_or,
                    options, points, difficulty
                )
                VALUES (
                    ${q.role}, ${q.step}, ${q.question_text_en}, ${q.question_text_hi}, 
                    ${q.question_text_mr || ''}, ${q.question_text_kn || ''}, ${q.question_text_te || ''}, ${q.question_text_or || ''},
                    ${q.options}::jsonb, ${q.points}, ${q.difficulty}
                )
            `;
        }
        console.log(`✅ Inserted ${questions.length} questions\n`);

        console.log('🎉 Migration completed successfully!');

    } catch (error) {
        console.error('❌ Migration failed:', error);
        process.exit(1);
    }
}

migrate();
